# Site settings
title: Guillermo RD
description: Guillermo R Delgad's Website.

# User settings
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
username: Guillermo RD
user_description: Guillermo R Delgad's Website.
user_title: iOS Developer
email: gelemias@gmail.com
github_username:  gelemias
linkedin_username: guillermoRD
resume: online-cv

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
